/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 11 12:54:16 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Calculator_ESTest extends Calculator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.sum(0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.sum(698, 698);
      assertEquals(1396, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.sub(698, 0);
      assertEquals(698, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.sub(0, 2988);
      assertEquals((-2988), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.sub(2584, 2584);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Calculator calculator0 = new Calculator();
      int int0 = calculator0.sum(2584, (-2988));
      assertEquals((-404), int0);
  }
}
